<?php /* Smarty version 2.6.7, created on 2011-10-15 02:44:26
         compiled from manage/home.tpl.html */

$this->_cache_serials['/home/bobeveal/public_html/memeja.com/flexycms/../var/memeja.com/templates_c/default/%%1A^1AB^1AB9F2F5%%home.tpl.html.inc'] = 'f9f49430a7d67d91a09dff4151e000b7';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'get_mod', 'manage/home.tpl.html', 2, false),)), $this); ?>
<?php
function _smarty_tplfunc_f9f49430a7d67d91a09dff4151e000b7_0(&$_smarty)
{
echo $_smarty->_plugins['function']['get_mod'][0][0]->get_mod(array('mod' => 'manage','mgr' => 'manage'), $_smarty);
}



?>
