<?php /* Smarty version 2.6.7, created on 2011-10-15 16:53:34
         compiled from user/right_pan.tpl.html */

$this->_cache_serials['/home/bobeveal/public_html/memeja.com/flexycms/../var/memeja.com/templates_c/default/%%35^35C^35CD1516%%right_pan.tpl.html.inc'] = '40eeffc17b76d86b645654a7746b9e3b';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'get_mod', 'user/right_pan.tpl.html', 15, false),)), $this); ?>
<?php
function _smarty_tplfunc_40eeffc17b76d86b645654a7746b9e3b_0(&$_smarty)
{
echo $_smarty->_plugins['function']['get_mod'][0][0]->get_mod(array('mod' => 'user','mgr' => 'user','choice' => 'friend_list','gmod' => 1), $_smarty);
}


function _smarty_tplfunc_40eeffc17b76d86b645654a7746b9e3b_1(&$_smarty)
{
echo $_smarty->_plugins['function']['get_mod'][0][0]->get_mod(array('mod' => 'paypal','mgr' => 'paypal','choice' => 'form'), $_smarty);
}



?>
