<?php /* Smarty version 2.6.7, created on 2012-04-07 17:13:12
         compiled from meme/home.tpl.html */

$this->_cache_serials['/home/bobeveal/public_html/memeja.com/flexycms/../var/memeja.com/templates_c/default/%%3A^3A7^3A710A60%%home.tpl.html.inc'] = 'e6267155acde4d5ebbb7211caa98f4f7';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'get_mod', 'meme/home.tpl.html', 2, false),)), $this); ?>
<?php
function _smarty_tplfunc_e6267155acde4d5ebbb7211caa98f4f7_0(&$_smarty)
{
echo $_smarty->_plugins['function']['get_mod'][0][0]->get_mod(array('mod' => 'meme','mgr' => 'meme'), $_smarty);
}



?>
