<?php /* Smarty version 2.6.7, created on 2011-10-14 10:50:01
         compiled from achievements/whatisMemeja.tpl.html */

$this->_cache_serials['/home/bobeveal/public_html/memeja.com/flexycms/../var/memeja.com/templates_c/default/%%3F^3F3^3F3AF2A3%%whatisMemeja.tpl.html.inc'] = 'c47ccad8dae3c89b3f2d91814f6c1771';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'get_mod', 'achievements/whatisMemeja.tpl.html', 6, false),)), $this); ?>
<?php
function _smarty_tplfunc_c47ccad8dae3c89b3f2d91814f6c1771_0(&$_smarty)
{
echo $_smarty->_plugins['function']['get_mod'][0][0]->get_mod(array('mod' => 'cms','mgr' => 'cms','choice' => 'show','code' => 'howtogetachievement'), $_smarty);
}



?>
