<?php /* Smarty version 2.6.7, created on 2011-10-15 17:35:36
         compiled from manage/home.tpl.html */

$this->_cache_serials['/home/bobeveal/public_html/memeja.com/flexycms/../var/memeja.com/templates_c/default/^%%1A^1AB^1AB9F2F5%%home.tpl.html.inc'] = '91f80e11c26c1a3b6d4a9305d12d6fdd';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'get_mod', 'manage/home.tpl.html', 2, false),)), $this); ?>
<?php
function _smarty_tplfunc_91f80e11c26c1a3b6d4a9305d12d6fdd_0(&$_smarty)
{
echo $_smarty->_plugins['function']['get_mod'][0][0]->get_mod(array('mod' => 'manage','mgr' => 'manage'), $_smarty);
}



?>
