<?php /* Smarty version 2.6.7, created on 2012-04-07 17:15:31
         compiled from user/home.tpl.html */

$this->_cache_serials['/home/bobeveal/public_html/memeja.com/flexycms/../var/memeja.com/templates_c/default/^%%1F^1F9^1F96D91B%%home.tpl.html.inc'] = '4c45f32197630c5c688daa25a8fefc6b';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'get_mod', 'user/home.tpl.html', 2, false),)), $this); ?>
<?php
function _smarty_tplfunc_4c45f32197630c5c688daa25a8fefc6b_0(&$_smarty)
{
echo $_smarty->_plugins['function']['get_mod'][0][0]->get_mod(array('mod' => 'user','mgr' => 'user'), $_smarty);
}



?>
