<?php /* Smarty version 2.6.7, created on 2012-01-11 07:43:26
         compiled from common/home.tpl.html */

$this->_cache_serials['C:/xampp/htdocs/flexycms/../var/memeja.com/templates_c/default\^%%45^454^45452386%%home.tpl.html.inc'] = '9483f82554b50bda2f7c82d0cc26eb40';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'get_mod', 'common/home.tpl.html', 2, false),)), $this); ?>
<?php
function _smarty_tplfunc_9483f82554b50bda2f7c82d0cc26eb40_0(&$_smarty)
{
echo $_smarty->_plugins['function']['get_mod'][0][0]->get_mod(array('mod' => 'user','mgr' => 'user'), $_smarty);
}



?>
