<?php /* Smarty version 2.6.7, created on 2012-04-07 17:12:43
         compiled from common/home.tpl.html */

$this->_cache_serials['/home/bobeveal/public_html/memeja.com/flexycms/../var/memeja.com/templates_c/default/^%%45^454^45452386%%home.tpl.html.inc'] = 'eafba3a13420c965b8d234ed76d6448b';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'get_mod', 'common/home.tpl.html', 2, false),)), $this); ?>
<?php
function _smarty_tplfunc_eafba3a13420c965b8d234ed76d6448b_0(&$_smarty)
{
echo $_smarty->_plugins['function']['get_mod'][0][0]->get_mod(array('mod' => 'user','mgr' => 'user'), $_smarty);
}



?>
