<?php /* Smarty version 2.6.7, created on 2011-10-15 16:53:33
         compiled from common/common.tpl.html */

$this->_cache_serials['/home/bobeveal/public_html/memeja.com/flexycms/../var/memeja.com/templates_c/default/^%%4F^4F7^4F7F9384%%common.tpl.html.inc'] = 'a15366e63fb7b2c65719357811f85b28';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'get_mod', 'common/common.tpl.html', 357, false),)), $this); ?>
<?php
function _smarty_tplfunc_a15366e63fb7b2c65719357811f85b28_0(&$_smarty)
{
echo $_smarty->_plugins['function']['get_mod'][0][0]->get_mod(array('mod' => 'question','mgr' => 'question','choice' => 'get_this_week_question'), $_smarty);
}



?>
