<?php /* Smarty version 2.6.7, created on 2012-01-10 10:08:04
         compiled from common/common.tpl.html */

$this->_cache_serials['C:/xampp/htdocs/flexycms/../var/memeja.com/templates_c/default\^%%4F^4F7^4F7F9384%%common.tpl.html.inc'] = 'a7fe02647ebc84c6f4ddbe64ec099d00';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'get_mod', 'common/common.tpl.html', 527, false),)), $this); ?>
<?php
function _smarty_tplfunc_a7fe02647ebc84c6f4ddbe64ec099d00_0(&$_smarty)
{
echo $_smarty->_plugins['function']['get_mod'][0][0]->get_mod(array('mod' => 'question','mgr' => 'question','choice' => 'get_this_week_question'), $_smarty);
}



?>
