<?php /* Smarty version 2.6.7, created on 2012-04-07 16:44:53
         compiled from achievements/home.tpl.html */

$this->_cache_serials['/home/bobeveal/public_html/memeja.com/flexycms/../var/memeja.com/templates_c/default/^%%86^860^86063F6A%%home.tpl.html.inc'] = '55aaf0c03ecb32cf412cf11696753261';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'get_mod', 'achievements/home.tpl.html', 2, false),)), $this); ?>
<?php
function _smarty_tplfunc_55aaf0c03ecb32cf412cf11696753261_0(&$_smarty)
{
echo $_smarty->_plugins['function']['get_mod'][0][0]->get_mod(array('mod' => 'achievements','mgr' => 'achievements'), $_smarty);
}



?>
