<?php /* Smarty version 2.6.7, created on 2011-10-15 11:07:57
         compiled from leaderboard/home.tpl.html */

$this->_cache_serials['/home/bobeveal/public_html/memeja.com/flexycms/../var/memeja.com/templates_c/default/^%%89^89C^89C17571%%home.tpl.html.inc'] = '99efa6982aa92b5427b8cd4c14a9c89d';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'get_mod', 'leaderboard/home.tpl.html', 2, false),)), $this); ?>
<?php
function _smarty_tplfunc_99efa6982aa92b5427b8cd4c14a9c89d_0(&$_smarty)
{
echo $_smarty->_plugins['function']['get_mod'][0][0]->get_mod(array('mod' => 'leaderboard','mgr' => 'leaderboard'), $_smarty);
}



?>
