<?php /* Smarty version 2.6.7, created on 2011-09-20 02:22:45
         compiled from duels/home.tpl.html */

$this->_cache_serials['/home/bobeveal/public_html/memeja.com/flexycms/../var/memeja.com/templates_c/default/^%%F4^F48^F484B3A4%%home.tpl.html.inc'] = '51c490ea49db59d00c21788199d0ccc7';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'get_mod', 'duels/home.tpl.html', 2, false),)), $this); ?>
<?php
function _smarty_tplfunc_51c490ea49db59d00c21788199d0ccc7_0(&$_smarty)
{
echo $_smarty->_plugins['function']['get_mod'][0][0]->get_mod(array('mod' => 'duels','mgr' => 'duels'), $_smarty);
}



?>
