<?php /* Smarty version 2.6.7, created on 2011-09-19 23:57:30
         compiled from admin/achievements/home.tpl.html */

$this->_cache_serials['/home/bobeveal/public_html/memeja.com/flexycms/../var/memeja.com/templates_admin_c//^%%23^238^238D3550%%home.tpl.html.inc'] = 'aed0df9bd5f2ac86360c2baeb295ec1a';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'get_mod', 'admin/achievements/home.tpl.html', 2, false),)), $this); ?>
<?php
function _smarty_tplfunc_aed0df9bd5f2ac86360c2baeb295ec1a_0(&$_smarty)
{
echo $_smarty->_plugins['function']['get_mod'][0][0]->get_mod(array('mod' => 'achievements','mgr' => 'achievements'), $_smarty);
}



?>
