flexymsg = {
	required_dob: "This field is required.",
	required: "<br/>This field is required.",	
	remote: "<br/>Please fix this field.",
	email: "<br/>Please enter a valid email address.",
	url: "<br/>Please enter a valid URL.",
	date: "<br/>Please enter a valid date.",
	dateISO: "<br/>Please enter a valid date (ISO).",
	number: "<br/>Please enter a valid number.",
	digits: "<br/>Please enter only digits.",
	creditcard: "<br/>Please enter a valid credit card number.",
	equalTo: "<br/>Please enter the same value again.",
	accept: "<br/>Please enter a value with a valid extension.",
	maxlength: "<br/>Please enter no more than {0} characters.",
	minlength: "<br/>Please enter at least {0} characters.",
	rangelength: "<br/>Please enter a value between {0} and {1} characters long.",
	range: "<br/>Please enter a value between {0} and {1}.",
	maxValue: "<br/>Please enter a value less than or equal to {0}.",
	minValue: "<br/>Please enter a value greater than or equal to {0}.",
	nodefind : "<br/> is not defined!",
	novalue : "<br/> return value is required!",
	customarray : "<br/>Custom function should return array!",
	customfcheck : "<br/>Custom function should be present in case of custom checking!"
};
