<?php /* Smarty version 2.6.7, created on 2011-12-26 23:23:18
         compiled from manage/home.tpl.html */

$this->_cache_serials['/opt/lampp/htdocs/flexycms/../var/localhost/templates_c/default/%%1A^1AB^1AB9F2F5%%home.tpl.html.inc'] = '6319514baa1fcbed63c46dfbbcc7733c';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'get_mod', 'manage/home.tpl.html', 2, false),)), $this); ?>
<?php
function _smarty_tplfunc_6319514baa1fcbed63c46dfbbcc7733c_0(&$_smarty)
{
echo $_smarty->_plugins['function']['get_mod'][0][0]->get_mod(array('mod' => 'manage','mgr' => 'manage'), $_smarty);
}



?>
