<?php /* Smarty version 2.6.7, created on 2012-06-08 06:32:11
         compiled from user/home.tpl.html */

$this->_cache_serials['C:/xampp/htdocs/flexycms/../var/localhost/templates_c/default\%%1F^1F9^1F96D91B%%home.tpl.html.inc'] = '695712d5691d0c38832d73ec8553b1d6';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'get_mod', 'user/home.tpl.html', 2, false),)), $this); ?>
<?php
function _smarty_tplfunc_695712d5691d0c38832d73ec8553b1d6_0(&$_smarty)
{
echo $_smarty->_plugins['function']['get_mod'][0][0]->get_mod(array('mod' => 'user','mgr' => 'user'), $_smarty);
}



?>
