<?php /* Smarty version 2.6.7, created on 2011-12-31 23:40:19
         compiled from user/home.tpl.html */

$this->_cache_serials['/opt/lampp/htdocs/flexycms/../var/localhost/templates_c/default/%%1F^1F9^1F96D91B%%home.tpl.html.inc'] = 'c728ca6a58ec6aea1849ad1af0f9e946';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'get_mod', 'user/home.tpl.html', 2, false),)), $this); ?>
<?php
function _smarty_tplfunc_c728ca6a58ec6aea1849ad1af0f9e946_0(&$_smarty)
{
echo $_smarty->_plugins['function']['get_mod'][0][0]->get_mod(array('mod' => 'user','mgr' => 'user'), $_smarty);
}



?>
