<?php /* Smarty version 2.6.7, created on 2011-12-10 23:33:08
         compiled from meme/home.tpl.html */

$this->_cache_serials['/opt/lampp/htdocs/flexycms/../var/localhost/templates_c/default/%%3A^3A7^3A710A60%%home.tpl.html.inc'] = '4ebbb459322bab95da9c898a1dcf1fb5';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'get_mod', 'meme/home.tpl.html', 2, false),)), $this); ?>
<?php
function _smarty_tplfunc_4ebbb459322bab95da9c898a1dcf1fb5_0(&$_smarty)
{
echo $_smarty->_plugins['function']['get_mod'][0][0]->get_mod(array('mod' => 'meme','mgr' => 'meme'), $_smarty);
}



?>
