<?php /* Smarty version 2.6.7, created on 2011-12-30 13:31:36
         compiled from achievements/whatisMemeja.tpl.html */

$this->_cache_serials['C:/xampp/htdocs/flexycms/../var/localhost/templates_c/default\%%3F^3F3^3F3AF2A3%%whatisMemeja.tpl.html.inc'] = '35189c520798d37bc4792a4d3c09bcb6';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'get_mod', 'achievements/whatisMemeja.tpl.html', 6, false),)), $this); ?>
<?php
function _smarty_tplfunc_35189c520798d37bc4792a4d3c09bcb6_0(&$_smarty)
{
echo $_smarty->_plugins['function']['get_mod'][0][0]->get_mod(array('mod' => 'cms','mgr' => 'cms','choice' => 'show','code' => 'howtogetachievement'), $_smarty);
}



?>
