<?php /* Smarty version 2.6.7, created on 2012-01-01 02:51:30
         compiled from achievements/whatisMemeja.tpl.html */

$this->_cache_serials['C:/xampp/htdocs/flexycms/../var/localhost/templates_c/default\%%3F^3F3^3F3AF2A3%%whatisMemeja.tpl.html.inc'] = 'a19728649412cd1e17da615d510fb793';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'get_mod', 'achievements/whatisMemeja.tpl.html', 12, false),)), $this); ?>
<?php
function _smarty_tplfunc_a19728649412cd1e17da615d510fb793_0(&$_smarty)
{
echo $_smarty->_plugins['function']['get_mod'][0][0]->get_mod(array('mod' => 'cms','mgr' => 'cms','choice' => 'show','code' => 'howtogetachievement'), $_smarty);
}



?>
