<?php /* Smarty version 2.6.7, created on 2011-10-19 10:33:26
         compiled from cms/home.tpl.html */

$this->_cache_serials['C:/xampp/htdocs/flexycms/../var/localhost/templates_c/default\%%41^414^4149CF9E%%home.tpl.html.inc'] = '7ddcde5f47c87330d5a48c03e3ea226e';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'get_mod', 'cms/home.tpl.html', 3, false),)), $this); ?>
<?php
function _smarty_tplfunc_7ddcde5f47c87330d5a48c03e3ea226e_0(&$_smarty)
{
echo $_smarty->_plugins['function']['get_mod'][0][0]->get_mod(array('mgr' => 'cms','mod' => 'cms'), $_smarty);
}



?>
