<?php /* Smarty version 2.6.7, created on 2011-12-18 07:19:43
         compiled from cms/home.tpl.html */

$this->_cache_serials['/opt/lampp/htdocs/flexycms/../var/localhost/templates_c/default/%%41^414^4149CF9E%%home.tpl.html.inc'] = 'a43af622098d2faf4a3d71558468dc7e';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'get_mod', 'cms/home.tpl.html', 3, false),)), $this); ?>
<?php
function _smarty_tplfunc_a43af622098d2faf4a3d71558468dc7e_0(&$_smarty)
{
echo $_smarty->_plugins['function']['get_mod'][0][0]->get_mod(array('mgr' => 'cms','mod' => 'cms'), $_smarty);
}



?>
