<?php /* Smarty version 2.6.7, created on 2011-10-17 00:07:16
         compiled from cms/home.tpl.html */

$this->_cache_serials['/opt/lampp/htdocs/flexycms/../var/localhost/templates_c/default/%%41^414^4149CF9E%%home.tpl.html.inc'] = 'eb240796b33d45d73d274d0e641fe5fa';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'get_mod', 'cms/home.tpl.html', 3, false),)), $this); ?>
<?php
function _smarty_tplfunc_eb240796b33d45d73d274d0e641fe5fa_0(&$_smarty)
{
echo $_smarty->_plugins['function']['get_mod'][0][0]->get_mod(array('mgr' => 'cms','mod' => 'cms'), $_smarty);
}



?>
