<?php /* Smarty version 2.6.7, created on 2011-12-31 12:51:33
         compiled from common/home.tpl.html */

$this->_cache_serials['/opt/lampp/htdocs/flexycms/../var/localhost/templates_c/default/%%45^454^45452386%%home.tpl.html.inc'] = 'dd667de9d5ae62d8af4ba5871c3161e0';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'get_mod', 'common/home.tpl.html', 2, false),)), $this); ?>
<?php
function _smarty_tplfunc_dd667de9d5ae62d8af4ba5871c3161e0_0(&$_smarty)
{
echo $_smarty->_plugins['function']['get_mod'][0][0]->get_mod(array('mod' => 'user','mgr' => 'user'), $_smarty);
}



?>
