<?php /* Smarty version 2.6.7, created on 2012-08-12 06:52:23
         compiled from common/common.tpl.html */

$this->_cache_serials['C:/xampp/htdocs/flexycms/../var/localhost/templates_c/default\%%4F^4F7^4F7F9384%%common.tpl.html.inc'] = 'c1f36d2662323bac9892174c6b9acef8';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('modifier', 'capitalize', 'common/common.tpl.html', 267, false),array('function', 'get_mod', 'common/common.tpl.html', 298, false),)), $this); ?>
<?php
function _smarty_tplfunc_c1f36d2662323bac9892174c6b9acef8_0(&$_smarty)
{
echo $_smarty->_plugins['function']['get_mod'][0][0]->get_mod(array('mod' => 'manage','mgr' => 'manage','choice' => 'my_meme_list','gmod' => 1), $_smarty);
}


function _smarty_tplfunc_c1f36d2662323bac9892174c6b9acef8_1(&$_smarty)
{
echo $_smarty->_plugins['function']['get_mod'][0][0]->get_mod(array('mod' => 'manage','mgr' => 'manage','choice' => 'tagged_memes','gmod' => 1), $_smarty);
}


function _smarty_tplfunc_c1f36d2662323bac9892174c6b9acef8_2(&$_smarty)
{
echo $_smarty->_plugins['function']['get_mod'][0][0]->get_mod(array('mod' => 'manage','mgr' => 'manage','choice' => 'my_meme_list','gmod' => 1), $_smarty);
}


function _smarty_tplfunc_c1f36d2662323bac9892174c6b9acef8_3(&$_smarty)
{
echo $_smarty->_plugins['function']['get_mod'][0][0]->get_mod(array('mod' => 'manage','mgr' => 'manage','choice' => 'tagged_memes','gmod' => 1), $_smarty);
}



?>
