<?php /* Smarty version 2.6.7, created on 2012-03-22 20:46:05
         compiled from achievements/home.tpl.html */

$this->_cache_serials['C:/xampp/htdocs/flexycms/../var/localhost/templates_c/default\%%86^860^86063F6A%%home.tpl.html.inc'] = '229304a2881b6c421f6878ec759ec1be';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'get_mod', 'achievements/home.tpl.html', 2, false),)), $this); ?>
<?php
function _smarty_tplfunc_229304a2881b6c421f6878ec759ec1be_0(&$_smarty)
{
echo $_smarty->_plugins['function']['get_mod'][0][0]->get_mod(array('mod' => 'achievements','mgr' => 'achievements'), $_smarty);
}



?>
