<?php /* Smarty version 2.6.7, created on 2011-12-26 21:34:28
         compiled from leaderboard/home.tpl.html */

$this->_cache_serials['/opt/lampp/htdocs/flexycms/../var/localhost/templates_c/default/%%89^89C^89C17571%%home.tpl.html.inc'] = '460cbe5778c2f533b65dd31263444ef7';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'get_mod', 'leaderboard/home.tpl.html', 2, false),)), $this); ?>
<?php
function _smarty_tplfunc_460cbe5778c2f533b65dd31263444ef7_0(&$_smarty)
{
echo $_smarty->_plugins['function']['get_mod'][0][0]->get_mod(array('mod' => 'leaderboard','mgr' => 'leaderboard'), $_smarty);
}



?>
