<?php /* Smarty version 2.6.7, created on 2011-12-30 07:30:24
         compiled from manage/right_pan_user.tpl.html */

$this->_cache_serials['/opt/lampp/htdocs/flexycms/../var/localhost/templates_c/default/%%C7^C7A^C7A2BBCC%%right_pan_user.tpl.html.inc'] = 'fd54830963cb95f0261025b32d90678f';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('modifier', 'capitalize', 'manage/right_pan_user.tpl.html', 16, false),array('function', 'get_mod', 'manage/right_pan_user.tpl.html', 32, false),)), $this); ?>
<?php
function _smarty_tplfunc_fd54830963cb95f0261025b32d90678f_0(&$_smarty)
{
echo $_smarty->_plugins['function']['get_mod'][0][0]->get_mod(array('mod' => 'manage','mgr' => 'manage','choice' => 'my_meme_list','gmod' => 1), $_smarty);
}



?>
