<?php /* Smarty version 2.6.7, created on 2012-06-05 01:44:17
         compiled from manage/right_pan_user.tpl.html */

$this->_cache_serials['C:/xampp/htdocs/flexycms/../var/localhost/templates_c/default\%%C7^C7A^C7A2BBCC%%right_pan_user.tpl.html.inc'] = 'd85f525e83420471334dd7c40d977b57';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('modifier', 'capitalize', 'manage/right_pan_user.tpl.html', 5, false),array('function', 'get_mod', 'manage/right_pan_user.tpl.html', 43, false),)), $this); ?>
<?php
function _smarty_tplfunc_d85f525e83420471334dd7c40d977b57_0(&$_smarty)
{
echo $_smarty->_plugins['function']['get_mod'][0][0]->get_mod(array('mod' => 'manage','mgr' => 'manage','choice' => 'my_meme_list','gmod' => 1), $_smarty);
}


function _smarty_tplfunc_d85f525e83420471334dd7c40d977b57_1(&$_smarty)
{
echo $_smarty->_plugins['function']['get_mod'][0][0]->get_mod(array('mod' => 'manage','mgr' => 'manage','choice' => 'my_favorites','gmod' => 1), $_smarty);
}



?>
