<?php /* Smarty version 2.6.7, created on 2012-06-12 06:33:31
         compiled from meme/meme_list.tpl.html */

$this->_cache_serials['C:/xampp/htdocs/flexycms/../var/localhost/templates_c/default\%%E1^E14^E141E5EE%%meme_list.tpl.html.inc'] = '5bc9ba0bdcc035e11b712a0e76a9e054';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'get_mod', 'meme/meme_list.tpl.html', 474, false),)), $this); ?>
<?php
function _smarty_tplfunc_5bc9ba0bdcc035e11b712a0e76a9e054_0(&$_smarty)
{
echo $_smarty->_plugins['function']['get_mod'][0][0]->get_mod(array('mod' => 'manage','mgr' => 'manage','choice' => 'my_meme_list','gmod' => 1), $_smarty);
}


function _smarty_tplfunc_5bc9ba0bdcc035e11b712a0e76a9e054_1(&$_smarty)
{
echo $_smarty->_plugins['function']['get_mod'][0][0]->get_mod(array('mod' => 'manage','mgr' => 'manage','choice' => 'tagged_memes','gmod' => 1), $_smarty);
}



?>
