<?php /* Smarty version 2.6.7, created on 2011-12-25 06:48:54
         compiled from manage/home.tpl.html */

$this->_cache_serials['/opt/lampp/htdocs/flexycms/../var/localhost/templates_c/default/^%%1A^1AB^1AB9F2F5%%home.tpl.html.inc'] = '58a9e1ba2f80e465953db6faff18fd2a';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'get_mod', 'manage/home.tpl.html', 2, false),)), $this); ?>
<?php
function _smarty_tplfunc_58a9e1ba2f80e465953db6faff18fd2a_0(&$_smarty)
{
echo $_smarty->_plugins['function']['get_mod'][0][0]->get_mod(array('mod' => 'manage','mgr' => 'manage'), $_smarty);
}



?>
