<?php /* Smarty version 2.6.7, created on 2012-06-26 08:30:27
         compiled from user/home.tpl.html */

$this->_cache_serials['C:/xampp/htdocs/flexycms/../var/localhost/templates_c/default\^%%1F^1F9^1F96D91B%%home.tpl.html.inc'] = '3b5db16f1e6d8532446bdb801a9d8b78';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'get_mod', 'user/home.tpl.html', 2, false),)), $this); ?>
<?php
function _smarty_tplfunc_3b5db16f1e6d8532446bdb801a9d8b78_0(&$_smarty)
{
echo $_smarty->_plugins['function']['get_mod'][0][0]->get_mod(array('mod' => 'user','mgr' => 'user'), $_smarty);
}



?>
