<?php /* Smarty version 2.6.7, created on 2011-12-14 12:22:19
         compiled from caption/home.tpl.html */

$this->_cache_serials['/opt/lampp/htdocs/flexycms/../var/localhost/templates_c/default/^%%2C^2C1^2C182F38%%home.tpl.html.inc'] = '040e72a37585e381037806830a9a1aaa';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'get_mod', 'caption/home.tpl.html', 2, false),)), $this); ?>
<?php
function _smarty_tplfunc_040e72a37585e381037806830a9a1aaa_0(&$_smarty)
{
echo $_smarty->_plugins['function']['get_mod'][0][0]->get_mod(array('mod' => 'caption','mgr' => 'caption'), $_smarty);
}



?>
