<?php /* Smarty version 2.6.7, created on 2011-12-20 04:08:27
         compiled from caption/home.tpl.html */

$this->_cache_serials['/opt/lampp/htdocs/flexycms/../var/localhost/templates_c/default/^%%2C^2C1^2C182F38%%home.tpl.html.inc'] = 'a67b8c70f5476ba701e970f02e93db35';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'get_mod', 'caption/home.tpl.html', 2, false),)), $this); ?>
<?php
function _smarty_tplfunc_a67b8c70f5476ba701e970f02e93db35_0(&$_smarty)
{
echo $_smarty->_plugins['function']['get_mod'][0][0]->get_mod(array('mod' => 'caption','mgr' => 'caption'), $_smarty);
}



?>
