<?php /* Smarty version 2.6.7, created on 2012-06-23 04:13:50
         compiled from meme/home.tpl.html */

$this->_cache_serials['C:/xampp/htdocs/flexycms/../var/localhost/templates_c/default\^%%3A^3A7^3A710A60%%home.tpl.html.inc'] = 'ed94bc0a54388c8edc06a89b4d92d9bf';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'get_mod', 'meme/home.tpl.html', 2, false),)), $this); ?>
<?php
function _smarty_tplfunc_ed94bc0a54388c8edc06a89b4d92d9bf_0(&$_smarty)
{
echo $_smarty->_plugins['function']['get_mod'][0][0]->get_mod(array('mod' => 'meme','mgr' => 'meme'), $_smarty);
}



?>
