<?php /* Smarty version 2.6.7, created on 2012-01-01 01:08:51
         compiled from common/common.tpl.html */

$this->_cache_serials['/opt/lampp/htdocs/flexycms/../var/localhost/templates_c/default/^%%4F^4F7^4F7F9384%%common.tpl.html.inc'] = 'd4570ce6b453a96e729cc66520973936';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'get_mod', 'common/common.tpl.html', 661, false),)), $this); ?>
<?php
function _smarty_tplfunc_d4570ce6b453a96e729cc66520973936_0(&$_smarty)
{
echo $_smarty->_plugins['function']['get_mod'][0][0]->get_mod(array('mod' => 'question','mgr' => 'question','choice' => 'get_this_week_question'), $_smarty);
}



?>
