<?php /* Smarty version 2.6.7, created on 2012-04-01 08:46:14
         compiled from achievements/home.tpl.html */

$this->_cache_serials['C:/xampp/htdocs/flexycms/../var/localhost/templates_c/default\^%%86^860^86063F6A%%home.tpl.html.inc'] = '7ed973bed6e43c5d3cbd73a00b96cefc';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'get_mod', 'achievements/home.tpl.html', 2, false),)), $this); ?>
<?php
function _smarty_tplfunc_7ed973bed6e43c5d3cbd73a00b96cefc_0(&$_smarty)
{
echo $_smarty->_plugins['function']['get_mod'][0][0]->get_mod(array('mod' => 'achievements','mgr' => 'achievements'), $_smarty);
}



?>
