<?php /* Smarty version 2.6.7, created on 2011-10-17 20:32:20
         compiled from leaderboard/home.tpl.html */

$this->_cache_serials['/opt/lampp/htdocs/flexycms/../var/localhost/templates_c/default/^%%89^89C^89C17571%%home.tpl.html.inc'] = 'bf42da259698d28a0fd29197d21a50cc';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'get_mod', 'leaderboard/home.tpl.html', 2, false),)), $this); ?>
<?php
function _smarty_tplfunc_bf42da259698d28a0fd29197d21a50cc_0(&$_smarty)
{
echo $_smarty->_plugins['function']['get_mod'][0][0]->get_mod(array('mod' => 'leaderboard','mgr' => 'leaderboard'), $_smarty);
}



?>
