<?php /* Smarty version 2.6.7, created on 2012-06-04 04:40:41
         compiled from leaderboard/home.tpl.html */

$this->_cache_serials['C:/xampp/htdocs/flexycms/../var/localhost/templates_c/default\^%%89^89C^89C17571%%home.tpl.html.inc'] = 'aa87618c4bf4e83276896d052fec0e2b';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'get_mod', 'leaderboard/home.tpl.html', 2, false),)), $this); ?>
<?php
function _smarty_tplfunc_aa87618c4bf4e83276896d052fec0e2b_0(&$_smarty)
{
echo $_smarty->_plugins['function']['get_mod'][0][0]->get_mod(array('mod' => 'leaderboard','mgr' => 'leaderboard'), $_smarty);
}



?>
