<?php /* Smarty version 2.6.7, created on 2012-01-04 22:11:59
         compiled from common/header.tpl.html */

$this->_cache_serials['C:/xampp/htdocs/flexycms/../var/localhost/templates_c/default\^%%9B^9B9^9B925569%%header.tpl.html.inc'] = '1838feb259089a8093fe87f1caf6e1f9';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'get_mod', 'common/header.tpl.html', 60, false),)), $this); ?>
<?php
function _smarty_tplfunc_1838feb259089a8093fe87f1caf6e1f9_0(&$_smarty)
{
echo $_smarty->_plugins['function']['get_mod'][0][0]->get_mod(array('mod' => 'paypal','mgr' => 'paypal','choice' => 'form'), $_smarty);
}



?>
